name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - name: Authentification Google Cloud
        run: echo '${{ secrets.GCP_CREDENTIALS }}' > gcp-creds.json
      - name: Recuperer les donnees DVC
        env:
          GOOGLE_APPLICATION_CREDENTIALS: gcp-creds.json
        run: dvc pull
      - run: pytest tests/ -v

  docker-build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build de l'image Docker
        run: docker build -t pneumoscan-ia .
      - name: Test dans le conteneur
        run: docker run pneumoscan-ia