name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - name: Authentification Google Cloud
        run: echo '${{ secrets.GCP_CREDENTIALS }}' > gcp-creds.json
      - name: Recuperer les donnees de test DVC
        env:
          GOOGLE_APPLICATION_CREDENTIALS: gcp-creds.json
        run: dvc pull data/dvc_sample.dvc
      - run: pytest tests/ -v

  docker-build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install dvc[gs]
      - name: Authentification Google Cloud
        run: echo '${{ secrets.GCP_CREDENTIALS }}' > gcp-creds.json
      - name: Recuperer les donnees de test DVC
        env:
          GOOGLE_APPLICATION_CREDENTIALS: gcp-creds.json
        run: dvc pull data/dvc_sample.dvc
      - name: Connexion au registre GitHub
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build de l'image Docker
        run: docker build -t ghcr.io/naynouna/projetsynth-sea62:latest .
      - name: Test dans le conteneur
        run: docker run -v ${{ github.workspace }}/data:/app/data ghcr.io/naynouna/projetsynth-sea62:latest
      - name: Publication sur le registre
        run: docker push ghcr.io/naynouna/projetsynth-sea62:latest
      - name: Authentification Google Cloud (sans cle)
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
      - name: Configuration de gcloud
        uses: google-github-actions/setup-gcloud@v2
      - name: Deploiement automatique sur Cloud Run
        run: gcloud run deploy pneumoscan-ia --image=ghcr.io/naynouna/projetsynth-sea62:latest --region=northamerica-northeast1 --platform=managed --allow-unauthenticated --port=5000 --command=python --args=-m,src.api.app