name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - name: Authentification Google Cloud
        run: echo '${{ secrets.GCP_CREDENTIALS }}' > gcp-creds.json
      - name: Recuperer les donnees DVC
        env:
          GOOGLE_APPLICATION_CREDENTIALS: gcp-creds.json
        run: dvc pull
      - run: pytest tests/ -v

  docker-build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Connexion au registre GitHub
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build de l'image Docker
        run: docker build -t ghcr.io/naynouna/projetsynth-sea62:latest .
      - name: Test dans le conteneur
        run: docker run ghcr.io/naynouna/projetsynth-sea62:latest
      - name: Publication sur le registre
        run: docker push ghcr.io/naynouna/projetsynth-sea62:latest